import "@/styles/globals.css";
import type { Metadata } from 'next';
import { Providers } from "./providers";
import { fontSans } from '@/config/fonts';
import { HeaderWrapper } from '@/components/header'
import { FooterWrapper } from "@/components/footer";
import clsx from "clsx";

export const metadata: Metadata = {
  title: 'Dexifier Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"max-h-full w-full " + clsx("font-sans antialiased", fontSans.className)}>
        <HeaderWrapper />
        <Providers>
          {children}
        </Providers>
        <FooterWrapper />
      </body>
    </html>
  )
}
